/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonkie;

import java.awt.Button;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author ACER
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_name = new javax.swing.JLabel();
        txt_hp = new javax.swing.JLabel();
        txt_affack = new javax.swing.JLabel();
        txt_defense = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        txt_skill6 = new javax.swing.JLabel();
        txt_skill7 = new javax.swing.JLabel();
        txt_skill8 = new javax.swing.JLabel();
        txt_skill9 = new javax.swing.JLabel();
        bt_name1 = new javax.swing.JButton();
        bt_name2 = new javax.swing.JButton();
        bt_name3 = new javax.swing.JButton();
        bt_name4 = new javax.swing.JButton();
        bt_name5 = new javax.swing.JButton();
        bt_name6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Pokemon");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 11, 171, 47));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Name  :   Primeape ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 91, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("HP       :  1000");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 119, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Affack :  300");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 147, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Defense :  100");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 173, -1, -1));

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Documents\\NetBeansProjects\\Pokemonkie\\src\\pokemonkie\\image\\057.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 252, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("counter");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Close Combat");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("Night Slash");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("Low Sweep");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 204));
        jLabel11.setText("Name  :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 204));
        jLabel12.setText("HP       :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 204));
        jLabel13.setText("Affack :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 204));
        jLabel14.setText("Defense :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        txt_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_name.setForeground(new java.awt.Color(0, 102, 255));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 91, 135, -1));

        txt_hp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_hp.setForeground(new java.awt.Color(0, 102, 255));
        getContentPane().add(txt_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 119, 135, -1));

        txt_affack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_affack.setForeground(new java.awt.Color(0, 102, 255));
        getContentPane().add(txt_affack, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 147, 135, -1));

        txt_defense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_defense.setForeground(new java.awt.Color(0, 102, 255));
        getContentPane().add(txt_defense, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 173, 135, -1));

        image1.setBackground(new java.awt.Color(255, 153, 204));
        getContentPane().add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 290, 250));

        txt_skill6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_skill6.setForeground(new java.awt.Color(255, 204, 204));
        getContentPane().add(txt_skill6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 144, 25));

        txt_skill7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_skill7.setForeground(new java.awt.Color(255, 153, 153));
        getContentPane().add(txt_skill7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 144, 23));

        txt_skill8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_skill8.setForeground(new java.awt.Color(255, 204, 204));
        getContentPane().add(txt_skill8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 151, 25));

        txt_skill9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_skill9.setForeground(new java.awt.Color(255, 153, 153));
        getContentPane().add(txt_skill9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 151, -1));

        bt_name1.setBackground(new java.awt.Color(204, 204, 255));
        bt_name1.setFont(new java.awt.Font("Anchan", 1, 14)); // NOI18N
        bt_name1.setForeground(new java.awt.Color(0, 0, 204));
        bt_name1.setText("Rhydon");
        bt_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_name1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 109, 100, 40));

        bt_name2.setBackground(new java.awt.Color(255, 204, 255));
        bt_name2.setFont(new java.awt.Font("Anchan", 1, 14)); // NOI18N
        bt_name2.setForeground(new java.awt.Color(204, 0, 204));
        bt_name2.setText("Exeggutor");
        bt_name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_name2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 100, 40));

        bt_name3.setBackground(new java.awt.Color(255, 204, 204));
        bt_name3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_name3.setForeground(new java.awt.Color(255, 0, 204));
        bt_name3.setText("Golem");
        bt_name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_name3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 100, 40));

        bt_name4.setBackground(new java.awt.Color(255, 255, 204));
        bt_name4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_name4.setForeground(new java.awt.Color(255, 102, 0));
        bt_name4.setText("Farfetchd");
        bt_name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_name4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 100, 40));

        bt_name5.setBackground(new java.awt.Color(204, 255, 204));
        bt_name5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_name5.setForeground(new java.awt.Color(51, 204, 0));
        bt_name5.setText("Machamp");
        bt_name5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_name5ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 100, 40));

        bt_name6.setBackground(new java.awt.Color(204, 255, 255));
        bt_name6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_name6.setForeground(new java.awt.Color(0, 204, 204));
        bt_name6.setText("Poliwrl");
        bt_name6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_name6ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 100, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 204));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 102));
        jLabel16.setText("เปลี่ยนตัว");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Documents\\NetBeansProjects\\Pokemonkie\\src\\pokemonkie\\image\\lugia.jpg")); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_name1ActionPerformed
        // TODO add your handling code here:
        Rhydon rhydon = new Rhydon();
        
        txt_name.setText(rhydon.name);
        txt_hp.setText(String.valueOf(rhydon.hp));
         txt_affack.setText(String.valueOf(rhydon.attack));
        txt_defense.setText(String.valueOf(rhydon.defense));
        
        txt_skill6.setText(rhydon.skillname[0]);
        txt_skill7.setText(rhydon.skillname[1]);
        txt_skill8.setText(rhydon.skillname[2]);
        txt_skill9.setText(rhydon.skillname[3]);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("image/112.png"));
                icon.getImage().flush();
                image1.setIcon( icon );
    }//GEN-LAST:event_bt_name1ActionPerformed

    private void bt_name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_name2ActionPerformed
        // TODO add your handling code here:
         Exeggutor exeggutor = new Exeggutor();
        
        txt_name.setText(exeggutor.name);
        txt_hp.setText(String.valueOf(exeggutor.hp));
        txt_affack.setText(String.valueOf(exeggutor.attack));
        txt_defense.setText(String.valueOf(exeggutor.defense));
        
        txt_skill6.setText(exeggutor.skillname[0]);
        txt_skill7.setText(exeggutor.skillname[1]);
        txt_skill8.setText(exeggutor.skillname[2]);
        txt_skill9.setText(exeggutor.skillname[3]);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("image/103.png"));
                icon.getImage().flush();
                image1.setIcon( icon );
    }//GEN-LAST:event_bt_name2ActionPerformed

    private void bt_name3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_name3ActionPerformed
        // TODO add your handling code here:
        Golem golem = new Golem();
        
        txt_name.setText(golem.name);
        txt_hp.setText(String.valueOf(golem.hp));
         txt_affack.setText(String.valueOf(golem.attack));
        txt_defense.setText(String.valueOf(golem.defense));
        
        txt_skill6.setText(golem.skillname[0]);
        txt_skill7.setText(golem.skillname[1]);
        txt_skill8.setText(golem.skillname[2]);
        txt_skill9.setText(golem.skillname[3]);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("image/076.png"));
                icon.getImage().flush();
                image1.setIcon( icon );
    }//GEN-LAST:event_bt_name3ActionPerformed

    private void bt_name4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_name4ActionPerformed
        // TODO add your handling code here:
       Farfatchd farfatchd = new Farfatchd();
        
        txt_name.setText(farfatchd.name);
        txt_hp.setText(String.valueOf(farfatchd.hp));
         txt_affack.setText(String.valueOf(farfatchd.attack));
        txt_defense.setText(String.valueOf(farfatchd.defense));
        
        txt_skill6.setText(farfatchd.skillname[0]);
        txt_skill7.setText(farfatchd.skillname[1]);
        txt_skill8.setText(farfatchd.skillname[2]);
        txt_skill9.setText(farfatchd.skillname[3]);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("image/083.png"));
                icon.getImage().flush();
                image1.setIcon( icon );
    }//GEN-LAST:event_bt_name4ActionPerformed

    private void bt_name5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_name5ActionPerformed
        // TODO add your handling code here:
        Machamp machamp = new Machamp();
        
        txt_name.setText(machamp.name);
        txt_hp.setText(String.valueOf(machamp.hp));
        txt_affack.setText(String.valueOf(machamp.attack));
        txt_defense.setText(String.valueOf(machamp.defense));
        
        txt_skill6.setText(machamp.skillname[0]);
        txt_skill7.setText(machamp.skillname[1]);
        txt_skill8.setText(machamp.skillname[2]);
        txt_skill9.setText(machamp.skillname[3]);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("image/068.png"));
                icon.getImage().flush();
                image1.setIcon( icon );
    }//GEN-LAST:event_bt_name5ActionPerformed

    private void bt_name6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_name6ActionPerformed
        // TODO add your handling code here:
       Poliwrl poliwrl = new Poliwrl();
        
        txt_name.setText(poliwrl.name);
        txt_hp.setText(String.valueOf(poliwrl.hp));
        txt_affack.setText(String.valueOf(poliwrl.attack));
        txt_defense.setText(String.valueOf(poliwrl.defense));
        
        txt_skill6.setText(poliwrl.skillname[0]);
        txt_skill7.setText(poliwrl.skillname[1]);
        txt_skill8.setText(poliwrl.skillname[2]);
        txt_skill9.setText(poliwrl.skillname[3]);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("image/061.png"));
                icon.getImage().flush();
                image1.setIcon( icon );
    }//GEN-LAST:event_bt_name6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_name1;
    private javax.swing.JButton bt_name2;
    private javax.swing.JButton bt_name3;
    private javax.swing.JButton bt_name4;
    private javax.swing.JButton bt_name5;
    private javax.swing.JButton bt_name6;
    private javax.swing.JLabel image1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel txt_affack;
    private javax.swing.JLabel txt_defense;
    private javax.swing.JLabel txt_hp;
    private javax.swing.JLabel txt_name;
    private javax.swing.JLabel txt_skill6;
    private javax.swing.JLabel txt_skill7;
    private javax.swing.JLabel txt_skill8;
    private javax.swing.JLabel txt_skill9;
    // End of variables declaration//GEN-END:variables
}
